---
# this file is written by yaml(yet-another-markup-language), "---" denotes the start of a piece of content

# pub_dataset_path: ground_truth
# priv_dataset_path: stat-15-data
# priv_dataset_path: accidential_drug_deaths

# parameters.json describes all the valid values corresponding to each attribute, no matter it is numerical or categorical 
# parameter_spec: ./data/parameters.json
# parameter_spec: ./data/parameters1.json


# you can set the identifier attribute's name  below
# in synthesis we will remove the column for privacy desire
# identifier: sim_individual_id
identifier: ID


# you can define the binning settings as you want
# the three line means [min,max,step] values for bin,
# referring to parameters1.json, we set as below 
numerical_binning:
  "Age":
    - 14
    - 87
    - 10
# numerical_binning:
#   "AGE":
#     - 20
#     - 105
#     - 5
#   "INCTOT":
#     - 0
#     - 105_000
#     - 5_000
#   "INCWAGE":
#     - 0
#     - 105_000
#     - 5_000
#   "INCWELFR":
#     - 0
#     - 105_000
#     - 5_000
#   "INCINVST":
#     - 0
#     - 105_000
#     - 5_000
#   "INCEARN":
#     - 0
#     - 105_000
#     - 5_000
#   "POVERTY":
#     - 0
#     - 520
#     - 20
#   "HHWT":
#     - 0
#     - 520
#     - 20
#   "PERWT":
#     - 0
#     - 520
#     - 20
# we change the settings all in type of [s,t,step]
#   "DEPARTS":
#     - 0
#     - 15
#     - 30
#     - 45
#   "ARRIVES":
#     - 0
#     - 15
#     - 30
#     - 45  

  # TODO: just a test
  # "DEPARTS":
  #   - 0
  #   - 45
  #   - 15
  # "ARRIVES":
  #   - 0
  #   - 45
  #   - 15

# you can define settings to group some attributes 
# specifically, define which attributes to group,  the count of combined values,
# the new grouped attribute's name and the valid combinations
# sicne they are tailored for specific datasets and in practice tricks for efficiency consideration
# currently we set them as NULL

grouping_attributes: {}
determined_attributes: {}


# but you can refer to below as a possible example 

# grouping_attributes:
#   - attributes:
#       - "SEX"
#       - "MARST"
#     num_values: 12
#     grouped_name: "SEX+MARST"
#     combinations:
#       - !!python/tuple [1, 1]
#       - !!python/tuple [1, 2]
#       - !!python/tuple [1, 3]
#       - !!python/tuple [1, 4]
#       - !!python/tuple [1, 5]
#       - !!python/tuple [1, 6]
#       - !!python/tuple [2, 1]
#       - !!python/tuple [2, 2]
#       - !!python/tuple [2, 3]
#       - !!python/tuple [2, 4]
#       - !!python/tuple [2, 5]
#       - !!python/tuple [2, 6]
#   - attributes:
#       - "HCOVANY"
#       - "HCOVPRIV"
#       - "HINSEMP"
#       - "HINSCAID"
#       - "HINSCARE"
#     num_values: 13
#     grouped_name: "HINS-COV"
#     combinations:
#       - !!python/tuple [1, 1, 1, 1, 1]
#       - !!python/tuple [2, 1, 1, 1, 1]
#       - !!python/tuple [2, 1, 1, 1, 2]
#       - !!python/tuple [2, 1, 1, 2, 1]
#       - !!python/tuple [2, 1, 1, 2, 2]
#       - !!python/tuple [2, 2, 1, 1, 1]
#       - !!python/tuple [2, 2, 1, 1, 2]
#       - !!python/tuple [2, 2, 1, 2, 1]
#       - !!python/tuple [2, 2, 1, 2, 2]
#       - !!python/tuple [2, 2, 2, 1, 1]
#       - !!python/tuple [2, 2, 2, 1, 2]
#       - !!python/tuple [2, 2, 2, 2, 1]
#       - !!python/tuple [2, 2, 2, 2, 2]
#   - attributes:
#       - "EMPSTATD"
#       - "WORKEDYR"
#       - "WRKLSTWK"
#     num_values: 28
#     grouped_name: "EMP"
#     combinations:
#       - !!python/tuple [0, 0, 0]
#       - !!python/tuple [10, 3, 2]
#       - !!python/tuple [30, 1, 1]
#       - !!python/tuple [30, 2, 1]
#       - !!python/tuple [30, 1, 3]
#       - !!python/tuple [30, 3, 1]
#       - !!python/tuple [10, 3, 3]
#       - !!python/tuple [20, 3, 1]
#       - !!python/tuple [20, 2, 1]
#       - !!python/tuple [30, 2, 3]
#       - !!python/tuple [30, 3, 3]
#       - !!python/tuple [12, 3, 1]
#       - !!python/tuple [20, 1, 1]
#       - !!python/tuple [12, 3, 2]
#       - !!python/tuple [14, 3, 2]
#       - !!python/tuple [20, 3, 3]
#       - !!python/tuple [30, 3, 2]
#       - !!python/tuple [20, 2, 3]
#       - !!python/tuple [12, 3, 3]
#       - !!python/tuple [20, 1, 3]
#       - !!python/tuple [10, 3, 1]
#       - !!python/tuple [14, 3, 3]
#       - !!python/tuple [30, 1, 2]
#       - !!python/tuple [30, 2, 2]
#       - !!python/tuple [15, 3, 1]
#       - !!python/tuple [14, 3, 1]
#       - !!python/tuple [15, 3, 3]
#       - !!python/tuple [20, 1, 2]
#   - attributes:
#       - "ABSENT"
#       - "LOOKING"
#     num_values: 10
#     grouped_name: "ABS+LOOK"
#     combinations:
#       - !!python/tuple [0, 0]
#       - !!python/tuple [1, 1]
#       - !!python/tuple [1, 2]
#       - !!python/tuple [1, 3]
#       - !!python/tuple [3, 1]
#       - !!python/tuple [3, 2]
#       - !!python/tuple [3, 3]
#       - !!python/tuple [4, 1]
#       - !!python/tuple [4, 2]
#       - !!python/tuple [4, 3]
#   - attributes:
#       - "AVAILBLE"
#       - "WRKRECAL"
#     num_values: 12
#     grouped_name: "AVA+RECAL"
#     combinations:
#       - !!python/tuple [0, 0]
#       - !!python/tuple [2, 1]
#       - !!python/tuple [2, 2]
#       - !!python/tuple [2, 3]
#       - !!python/tuple [3, 1]
#       - !!python/tuple [3, 2]
#       - !!python/tuple [3, 3]
#       - !!python/tuple [4, 1]
#       - !!python/tuple [4, 2]
#       - !!python/tuple [4, 3]
#       - !!python/tuple [5, 1]
#       - !!python/tuple [5, 2]
#       - !!python/tuple [5, 3]


# you can detect some attributes whose value can be determined by others to help the efficiency
# in that case, write down the mapping details below

# determined_attributes:
#   "EMPSTAT":
#     by: "EMPSTATD"
#     mapping:
#       20: 2
#       30: 3
#       0: 0
#     default: 1
#   "LABFORCE":
#     by: "EMPSTATD"
#     mapping:
#       30: 1
#       0: 0
#     default: 2
